@echo off
echo Starting Onder Muhendislik 3D Showcase...
echo.
echo Configuring Windows Firewall...
echo Opening port 3000 for frontend...
netsh advfirewall firewall add rule name="3D Showcase Frontend Port 3000" dir=in action=allow protocol=TCP localport=3000
echo Opening port 2999 for backend...
netsh advfirewall firewall add rule name="3D Showcase Backend Port 2999" dir=in action=allow protocol=TCP localport=2999
echo.
echo Installing dependencies...
call npm install
echo.
echo Starting backend server and frontend...
call npm run dev:full
pause